"""Data source module for obtaining user configuration information from various sources.

This module contains the following main functions:
- Get occupation data from local files
- Generate realistic geographic location information
- Generate age information
- Generate gender information
"""

import json
import os
import random
from typing import Dict, List, Optional, Union, Any
from geonamescache import GeonamesCache
from config import get_completion, parse_gpt_response, parse_json_response, extract_json_from_markdown, parse_nested_json_response

_occupations_cache = None

def get_occupations() -> List[str]:
    """Get occupation data from local file.

    Read occupation list from predefined JSON file. Uses caching to avoid repeated file reads.
    Returns empty list if file read fails.

    Returns:
        List[str]: Occupation list. Returns empty list if retrieval fails
    """
    global _occupations_cache

    if _occupations_cache is not None:
        return _occupations_cache

    try:
        # Use data folder under project root directory
        project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
        file_path = os.path.join(project_root, 'data', 'occupations_english.json')
        with open(file_path, 'r', encoding='utf-8') as f:
            _occupations_cache = json.load(f)
        return _occupations_cache
    except Exception as e:
        print(f"Error loading occupations data: {e}")
        return []

def generate_age_info() -> Dict[str, Union[int, str]]:
    """Generate age information.

    First randomly generate an age in the 7-85 range, then determine the corresponding age group.
    Age groups include: toddler, child, adolescent, young_adult, adult, middle_aged, senior.

    Returns:
        Dict[str, Union[int, str]]: Dictionary containing:
            - age: Specific age (integer)
            - age_group: Age group category
    """
    # First randomly generate age
    age = random.randint(7, 85)

    # Determine age group based on age
    if age <= 6:
        age_group = "toddler"
    elif age <= 12:
        age_group = "child"
    elif age <= 19:
        age_group = "adolescent"
    elif age <= 29:
        age_group = "young_adult"
    elif age <= 45:
        age_group = "adult"
    elif age <= 65:
        age_group = "middle_aged"
    else:
        age_group = "senior"

    return {
        "age": age,
        "age_group": age_group
    }

def generate_career_info(age: int) -> Dict[str, str]:
    """Generate career-related information.

    Determine career generation method based on age:
    - For people under 18 or over 65, career status is generated by GPT based on age
    - For other age groups, randomly select from local occupation database

    Args:
        age: Age

    Returns:
        Dict[str, str]: Career-related information containing occupation status
    """
    if age < 18 or age > 65:
        # For under 18 or over 65, career status is generated by GPT
        prompt = f"Generate an appropriate occupation or status for a {age} year old person. "
        if age < 18:
            prompt += "Consider that the individuals are likely in school or engaged in youth activities. They may not have any formal occupation. If appropriate, you can mention their student status or indicate they have no occupation yet. Only in some cases, consider potential interest in early employment opportunities, internships, or non-traditional educational paths."
        else:  # age > 65
            prompt += "Consider they might be retired but could still be active in various ways."

        messages = [
            {"role": "system", "content": "You are an AI that generates realistic occupation statuses based on age. Respond with just the status, no explanation."},
            {"role": "user", "content": prompt}
        ]

        status = get_completion(messages)
        if not status:
            return {"status": ""}
        return {"status": status}

    # Other age groups select from occupation database
    occupations = get_occupations()
    if not occupations:
        return {"status": ""}

    career_status = random.choice(occupations)
    return {"status": career_status}

# def generate_location() -> Dict[str, str]:
#     """Generate realistic geographic location information.
#
#     Use GeoNames database to randomly select a country and city.
#
#     Returns:
#         Dict[str, str]: Dictionary containing:
#             - country: Country name
#             - city: City name
#     """
#     gc = GeonamesCache()
#
#     # Get all countries
#     countries = gc.get_countries()
#     country_code = random.choice(list(countries.keys()))
#     country = countries[country_code]
#
#     # Get all cities for selected country
#     cities = gc.get_cities()
#     country_cities = [city for city in cities.values() if city['countrycode'] == country_code]
#
#     if not country_cities:
#         return {
#             "country": country['name'],
#             "city": "Unknown City"
#         }
#
#     # Randomly select a city
#     city_data = random.choice(country_cities)
#
#     return {
#         "country": country['name'],
#         "city": city_data['name']
#     }


def generate_location(country_code: str = None) -> Dict[str, str]:
    """
    Generate geographic location information for a random city.

    Args:
        country_code: Optional ISO country code (e.g., "US", "GB", "IN").
                      If not provided, randomly selects from diverse countries.

    Returns:
        Dict[str, str]:
            - country: Country name
            - city: Random city name from that country
    """
    gc = GeonamesCache()
    countries = gc.get_countries()

    # If no country specified, randomly select from diverse list
    if not country_code:
        diverse_countries = ["US", "GB", "CA", "AU", "DE", "FR", "IN", "JP", "BR", "SG"]
        country_code = random.choice(diverse_countries)

    # Validate country code exists
    if country_code not in countries:
        print(f"Warning: Country code '{country_code}' not found, defaulting to US")
        country_code = "US"

    country = countries[country_code]

    # Filter all cities for selected country
    cities = gc.get_cities()
    country_cities_list = [
        city for city in cities.values()
        if city["countrycode"] == country_code
    ]

    # Fallback if no cities found
    if not country_cities_list:
        fallback_cities = {
            "US": "New York", "GB": "London", "CA": "Toronto", "AU": "Sydney",
            "DE": "Berlin", "FR": "Paris", "IN": "Mumbai", "JP": "Tokyo",
            "BR": "São Paulo", "SG": "Singapore"
        }
        return {"country": country["name"], "city": fallback_cities.get(country_code, "Unknown")}

    # Randomly select a city
    city_data = random.choice(country_cities_list)
    return {"country": country["name"], "city": city_data["name"]}


def generate_gender() -> str:
    """Randomly generate gender (male/female)"""
    return random.choice(['male', 'female'])


def generate_personal_values(age: int, gender: str, occupation: str, location: Dict[str, str]) -> Dict[str, str]:
    """Generate personal values using GPT based on demographic information.

    First randomly select a value type from positive, negative, neutral,
    then put this type in the prompt and let GPT generate specific value details.

    Args:
        age: Person's age
        gender: Person's gender
        occupation: Person's occupation
        location: Dictionary containing 'city' and 'country' keys

    Returns:
        Dictionary containing 'values_orientation' key with values description
    """
    # Randomly select value type
    value_type = random.choice(['positive', 'negative', 'neutral'])
    
    prompt = f"""
    Generate a concise description of a person's core values and belief system based on:
    Age: {age}, Gender: {gender}, Occupation: {occupation}, Location: {location['city']}, {location['country']}

    IMPORTANT: This person has a {value_type.upper()} value system. Their values may be entirely consistent with their personal background or may conflict with it. Avoid introducing unnecessary contrasts or contradictions in their beliefs. Try to avoid being related to the community as much as possible. Avoid using words with similar meanings to ‘balance’ and ‘balance’.

    Please generate a short phrase that clearly captures the essence of this person's core values and beliefs without adding conflicting ideas or turnarounds.

    CRITICAL: You must format your response EXACTLY as a valid JSON object with this structure:
    {{
        "values_orientation": "short phrase describing their values"
    }}

    DO NOT include any text before or after the JSON. The response must be parseable by json.loads().
    """
    
    messages = [
        {"role": "system", "content": "You are an assistant that generates realistic human value systems in ONE SENTENCE, including both positive and negative values. You ALWAYS respond with valid JSON objects that can be parsed by json.loads()."}, 
        {"role": "user", "content": prompt}
    ]
    
    try:
        response = get_completion(messages, temperature=0.8)

        # Use parsing function from config.py
        result = parse_gpt_response(
            response,
            expected_fields=["values_orientation"],
            field_defaults={"values_orientation": ""}
        )

        return {
            "values_orientation": result.get("values_orientation") or response.strip()
        }
    except Exception as e:
        print(f"\nError in generate_personal_values: {e}")
        raise




def generate_life_attitude(age: int = None, gender: str = None, occupation: str = None,
                        location: Dict[str, str] = None, values_orientation: str = None) -> Dict[str, Union[str, Dict, bool]]:
    """Generate life attitude using GPT based on demographic information and personal values.

    This function uses GPT to generate a person's life attitude based on age, gender, occupation,
    location and personal values. The generated attitude can be positive, neutral or negative.

    Args:
        age: Person's age
        gender: Person's gender
        occupation: Person's occupation
        location: Dictionary containing 'city' and 'country' keys
        values_orientation: Personal values description

    Returns:
        Dict: Dictionary containing:
            - attitude: String representing user's life attitude
            - attitude_details: Details about how this attitude manifests
            - coping_mechanism: How the person deals with life challenges
    """

    # Create prompt
    prompt = f"""
    Generate specific attributes about a person's life attitude based on the following information:
    
    Age: {age}
    Gender: {gender}
    Occupation: {occupation}
    Location: {location['city']}, {location['country']}
    Core Values: {values_orientation}
    
    IMPORTANT: This person's attitude toward life can be positive, neutral, or negative. In a negative state, they may hold a pessimistic, cynical, or even nihilistic view of life. Avoid involving concepts such as community or balance. Avoid using words with similar meanings to ‘balance’ and ‘balance’.
    
    I need you to generate ONLY the following specific attributes, each expressed as a single sentence:
    
    1. attitude: A single, concise sentence (5-10 words) describing their overall life attitude
    2. attitude_details: A single sentence (15-20 words) explaining how this attitude manifests in their daily life
    3. coping_mechanism: A single sentence (5-10 words) describing how they deal with challenges
    
    CRITICAL: You must format your response EXACTLY as a valid JSON object with this structure:
    {{"attitude": "single sentence", "attitude_details": "single sentence", "coping_mechanism": "single sentence"}}
    
    DO NOT include any text before or after the JSON. The response must be parseable by json.loads().
    """
    
    messages = [
        {"role": "system", "content": "You are an assistant that generates realistic human life attitudes in ONE SENTENCE, including positive, neutral, and negative outlooks. You ALWAYS respond with valid JSON objects that can be parsed by json.loads()."}, 
        {"role": "user", "content": prompt}
    ]
    
    try:
        response = get_completion(messages, temperature=0.8)

        # Use parsing function from config.py
        result = parse_gpt_response(
            response,
            expected_fields=["attitude", "attitude_details", "coping_mechanism"],
            field_defaults={
                "attitude": "",
                "attitude_details": "",
                "coping_mechanism": ""
            }
        )

        # Check for empty values
        for field in ["attitude", "attitude_details", "coping_mechanism"]:
            if not result[field]:
                raise ValueError(f"Missing required field: {field}")

        attitude = result["attitude"]
        attitude_details = result["attitude_details"]
        coping_mechanism = result["coping_mechanism"]
    except Exception as e:
        print(f"\nError in generate_life_attitude: {e}")
        raise

    # Return result
    return {
        "attitude": attitude,
        "attitude_details": attitude_details,
        "coping_mechanism": coping_mechanism
    }

def generate_personal_story(age: int, gender: str, occupation: str, location: Dict[str, str],
                                    values_orientation: str, life_attitude: Dict[str, str]) -> Dict[str, str]:
    """Generate personal story based on person's basic information.

    Use GPT to generate a detailed story based on age, gender, occupation, location, values and life attitude.
    The story can contain various positive or negative experiences, including extreme situations.

    Args:
        age: Person's age
        gender: Person's gender
        occupation: Person's occupation
        location: Dictionary containing 'city' and 'country' keys
        values_orientation: Personal values description
        life_attitude: Life attitude information dictionary

    Returns:
        Dict: Dictionary containing:
            - personal_story: Personal story description
    """
    # Extract life attitude information
    attitude = life_attitude.get("attitude", "")
    attitude_category = life_attitude.get("attitude_category", "neutral")

    # Create prompt
    # Randomly decide how many stories to generate
    num_stories = random.randint(1, 3)
    
    prompt = f"""
    Generate {num_stories} concise personal stories for a person with the following characteristics:
    
    Age: {age}
    Gender: {gender}
    Occupation: {occupation}
    Location: {location['city']}, {location['country']}
    Core Values: {values_orientation}
    Life Attitude: {attitude} ({attitude_category})
    
    IMPORTANT: The story can be positive, negative, or a mix of both. Please do not avoid including life experiences that may be controversial or have negative consequences. The narration should be as specific as possible, objective, and free from any subjective comments or value judgments. The stories that unfold should be closely related to their country and region, reflecting events that could genuinely happen to the people there. This could be a random event unrelated to the background, or a significant turning point in their life. Please avoid including anything related to community building.
    
    Please provide {num_stories} brief personal stories (each 150-200 words).
    
    CRITICAL: You must format your response EXACTLY as a valid JSON object with this structure:
    {{"personal_stories": ["story 1", "story 2", ...]}}
    
    DO NOT include any text before or after the JSON. The response must be parseable by json.loads().
    """
    messages = [
        {"role": "system", "content": "You are an assistant that generates concise realistic personal stories, including both positive and negative life experiences. You ALWAYS respond with valid JSON objects that can be parsed by json.loads()."}, 
        {"role": "user", "content": prompt}
    ]
    
    try:
        response = get_completion(messages, temperature=0.8)

        # Parse JSON response, only get personal stories
        result = parse_gpt_response(
            response,
            expected_fields=["personal_stories"],
            field_defaults={
                "personal_stories": []
            }
        )

        # Process multi-story format
        stories = result["personal_stories"]

        # Ensure we have data
        if not stories:
            raise ValueError("Failed to generate personal stories")

        # Convert multi-story format to unified format
        # Concatenate all stories with separator
        combined_story = "\n\n".join([f"Story {i+1}: {story}" for i, story in enumerate(stories)])

        return {
            "personal_story": combined_story
        }
    except Exception as e:
        print(f"\nError in generate_personal_story: {e}")
        raise

def generate_interests_and_hobbies(personal_story: Dict[str, Any]) -> Dict[str, Any]:
    """Generate interests and hobbies list based on person's story.

    Based on person's personal story and key life events, generate interests and hobbies list,
    which can include good or bad habits. Strictly based on story content, generates 2-3 interests.

    Args:
        personal_story: Person's personal story dictionary containing "personal_story" and "key_life_events" fields

    Returns:
        Dict: Dictionary containing:
            - interests: Interests and hobbies list (2-3 items)
    """
    # Ensure we have personal story data
    if not personal_story or not isinstance(personal_story, dict):
        raise ValueError("Personal story data required to generate interests and hobbies")

    personal_story_data = personal_story

    # Extract story and key events
    story_text = personal_story_data.get("personal_story", "")

    # Create prompt
    prompt = f"""
   Based on the following personal story and key life events, infer two to three hobbies or interests this person might use to relax. These activities can be positive or negative and may include non-traditional, controversial, or unexpected ones, such as various sports, traveling, or even smoking, drinking, or using marijuana. Please make inferences about the person’s possible interests based on the story, rather than simply extracting them directly from the story. 
   
     Personal Story: {story_text}

     IMPORTANT: Avoid including anything related to community-building activities.
     
    Please extract 2 hobbies or interests based on these reflections and format your response as a JSON object:

     {{
        "interests": ["interest1", "interest2"]
     }}

    DO NOT include any text before or after the JSON. The response must be parseable by json.loads().
    """
    
    messages = [
        {"role": "system", "content": "You are an assistant that extracts realistic interests and hobbies from a person's life story, including both positive activities and negative habits. You ALWAYS respond with valid JSON objects that can be parsed by json.loads()."}, 
        {"role": "user", "content": prompt}
    ]
    
    try:
        response = get_completion(messages, temperature=0.2)

        # Use parsing function from config.py (already imported at top)
        result = parse_gpt_response(
            response,
            expected_fields=["interests"],
            field_defaults={"interests": []}
        )

        # Get interests list
        interests = result.get("interests", [])
    except Exception as e:
        # Log error and re-raise
        print(f"\nError in generate_interests_and_hobbies: {e}")
        raise

    # Output generated interests count info
    print(f"\nInfo: Generated interests count: {len(interests)}")

    # Return result
    return {
        "interests": interests
    }